import { Router } from 'express';
import activateMembership from './activateMembership';
import applyInviteCode from './applyInviteCode';
import calculatePrice from './calculatePrice';
import checkJobSaved from './checkJobSaved';
import checkMemberStatus from './checkMemberStatus';
import clearAllSearchConditions from './clearAllSearchConditions';
import createOrder from './createOrder';
import deleteSearchCondition from './deleteSearchCondition';
import getFeaturedJobList from './getFeaturedJobList';
import getGeneratedResumes from './getGeneratedResumes';
import getJobDetail from './getJobDetail';
import getMemberSchemes from './getMemberSchemes';
import getPhoneNumber from './getPhoneNumber';
import getPublicJobList from './getPublicJobList';
import getSavedJobs from './getSavedJobs';
import getSavedSearchConditions from './getSavedSearchConditions';
import initUser from './initUser';
import payCallback from './payCallback';
import saveJob from './saveJob';
import saveResumeRecord from './saveResumeRecord';
import saveSearchCondition from './saveSearchCondition';
import searchJobs from './searchJobs';
import systemConfig from './systemConfig';
import unsaveJob from './unsaveJob';
import updateOrderStatus from './updateOrderStatus';
import updateUserLanguage from './updateUserLanguage';
import updateUserProfile from './updateUserProfile';
import generateInviteCode from './generateInviteCode';
import searchUniversities from './searchUniversities';
import searchMajors from './searchMajors';
import batchSaveJobs from './batchSaveJobs';
import login from './login';
import upload from './upload';

const router = Router();

// Mount all interface routers
router.use('/api', activateMembership);
router.use('/api', applyInviteCode);
router.use('/api', batchSaveJobs);
router.use('/api', calculatePrice);
router.use('/api', checkJobSaved);
router.use('/api', checkMemberStatus);
router.use('/api', clearAllSearchConditions);
router.use('/api', createOrder);
router.use('/api', payCallback);
router.use('/api/search', deleteSearchCondition);
router.use('/api', getFeaturedJobList);
router.use('/api', getGeneratedResumes);
router.use('/api', getJobDetail);
router.use('/api', generateInviteCode);
router.use('/api', getMemberSchemes);
router.use('/api', getPhoneNumber);
router.use('/api', getPublicJobList);
router.use('/api', getSavedJobs);
router.use('/api/search', getSavedSearchConditions);
router.use('/api', initUser);
router.use('/api', login);
router.use('/api', saveJob);
router.use('/api', saveResumeRecord);
router.use('/api', saveSearchCondition);
router.use('/api', searchJobs);
router.use('/api', searchMajors);
router.use('/api', searchUniversities);
router.use('/api', systemConfig);
router.use('/api', unsaveJob);
router.use('/api', updateOrderStatus);
router.use('/api', updateUserLanguage);
router.use('/api', updateUserProfile);
router.use('/api', upload);

export default router;
